name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Docker to ACR
      run: docker login "cheastuscr.azurecr.io"  -u "cheastuscr" -p "phs8zEYVCk0kXQPVPdpXTXk74M43EwcJfh+i66B1YN+ACRCztjpa"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag cheastuscr.azurecr.io/chwiki:latest
    - name: Push to ACR
      run: docker push cheastuscr.azurecr.io/chwiki:latest

